# Generated by Django 5.2.15 on 2026-06-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rules_text', models.TextField(blank=True, default='Здесь будут размещены правила сайта.', verbose_name='Правила')),
                ('contacts_text', models.TextField(blank=True, default='Служба поддержки. Если у вас есть вопросы, свяжитесь с Администрацией.', verbose_name='Контакты')),
                ('footer_year_start', models.PositiveIntegerField(default=2021, verbose_name='Год начала (футер)')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
